
---
- name: Install Apache and Upload my Web Page (practic delegate tasks)
  hosts: all
  become: yes

  vars:
    my_text: "Vsem serdechnyi"

  tasks:
  - name: Ping my servers
    ping:

  - name: Unregister Server from Load Balancer
    shell: echo This server {{ inventory_hostname }} was deregister from our Load Balancer, node name is {{ ansible_nodename }} >> /home/log.txt
    delegate_to: 127.0.0.1

  - name: Create file1
    copy:
      dest: /home/file1.txt
      content: |
        This is File 1
        On English - "Hello World"
        on Russian - {{ my_text }}
    delegate_to: linux_test

  - name: Create file2
    copy:
      dest: /home/file2.txt
      content: |
        This is File 2
        On English - "Hello World"
        on Russian - {{ my_text }}

  - name: Reboot my servers
    shell: sleep 3 && reboot now
    async: 1
    poll: 0

  - name: Wait till my server will come up online
    wait_for:
      host: "{{ inventory_hostname }}"
      state: started
      delay: 5
      timeout: 60
    delegate_to: 127.0.0.1
