
---
- name: Ansible Lesson 19 - error interception
  hosts: all
  any_errors_fatal: true
  become: yes

  tasks:
  - name: Install treeee
    apt: name=treeee state=latest
    ignore_errors: yes # in priority over any_errors_fatal

  - name: Input text
    shell: echo "HelloWorld"
    register: result
    failed_when: "'World' in result.stdout"

  - debug:
      var: result

  - name: Input text#2
    shell: echo "Zdorova, epta"
