
---
- name: loops PlayBook
  hosts: linux_test
  become: yes

  tasks:
  - name: Say Hello to all
    debug: msg="Hello {{ item }}"
    loop:
      - "Vasya"
      - "Masha"
      - "Dany"

  - name: Loop Until example
    shell: echo -n Z >> myfile.txt && cat myfile.txt
    register: output
    until: output.stdout.find("ZZZZ") == false
    delay: 2
    retries: 10

  - name: Print output
    debug:
      var: output.stdout

